labels:
  language: golang

version:
  semver:
    major: 0
    minor: 1

stages:
  build:
    image: golang:1.13.6
    env:
      CGO_ENABLED: 0
      GOOS: linux
    commands:
    - mkdir -p publish
    - go get -v github.com/ianlancetaylor/cgosymbolizer
    - go test ./pkg/cmd/cockroach/...
    - go build -a -installsuffix cgo -o ./publish ./pkg/cmd/cockroach

  bake:
    image: extensions/docker:stable
    action: build
    inline: |
      FROM scratch

      COPY ${ESTAFETTE_GIT_NAME} /
      COPY ca-certificates.crt /etc/ssl/certs/
      
      ENTRYPOINT ["/${ESTAFETTE_GIT_NAME}"]
    repositories:
    - jsalverda
    path: ./publish
    copy:
    - /etc/ssl/certs/ca-certificates.crt

  check-container:
    parallelStages:
      check-efficiency:
        image: extensions/docker:stable
        action: dive
        repositories:
        - jsalverda

      vulnerability-scan:
        image: extensions/docker:stable
        action: trivy
        repositories:
        - jsalverda

  push-to-docker-hub:
    image: extensions/docker:stable
    action: push
    repositories:
    - jsalverda